name: 🚀 Tests Automatisés

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: sortir_user_adm
          POSTGRES_PASSWORD: 1793
          POSTGRES_DB: sortir_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U sortir_user_adm"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: 📥 Cloner le repo
        uses: actions/checkout@v3

      - name: 📦 Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: 📜 Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🚀 Configurer la base de données
        env:
          DATABASE_URL: postgresql://sortir_user_adm:1793@localhost/sortir_db
        run: |
          python -c "from app import db, create_app; app = create_app(); with app.app_context(): db.create_all()"

      - name: 🔥 Lancer les tests unitaires
        env:
          DATABASE_URL: postgresql://sortir_user_adm:1793@localhost/sortir_db
          JWT_SECRET_KEY: "super-secret-key"
        run: |
          python -m unittest discover tests -v
