name: Tests API

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # 🔹 Vérifie que c'est bien 3.8+

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Vérifier la version de Python
        run: python --version

      - name: Initialisation de la base de données
        run: |
          python -c "from app import create_app; app = create_app(); from app import db; app.app_context().push(); db.create_all()"

      - name: Exécuter les tests
        run: python -m unittest discover tests -v
