name: Tests API

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15  # ✅ Utilisation d'un conteneur PostgreSQL
        env:
          POSTGRES_USER: sortir_user_adm
          POSTGRES_PASSWORD: 1793
          POSTGRES_DB: sortir_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install psycopg2-binary  # 🔥 Assure-toi que c'est bien installé

      - name: Initialisation de la base de données
        env:
          DATABASE_URL: "postgresql://sortir_user_adm:1793@localhost:5432/sortir_db"
        run: |
          python -c "from app import create_app; app = create_app(); from app import db; app.app_context().push(); db.create_all()"

      - name: Exécuter les tests
        env:
          DATABASE_URL: "postgresql://sortir_user_adm:1793@localhost:5432/sortir_db"
        run: python -m unittest discover tests -v
